// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkHZmw8ggw0KOGm9WiN4YCY_9Mu0cxrs0',
    appId: '1:511882466709:web:ac53a536c7dd6642b9529c',
    messagingSenderId: '511882466709',
    projectId: 'sugar-2474f',
    authDomain: 'sugar-2474f.firebaseapp.com',
    storageBucket: 'sugar-2474f.appspot.com',
    measurementId: 'G-8NDS48JVP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD34nhy85UdaA7nS64bh_h7JgJCcSkg40',
    appId: '1:511882466709:android:95f84a6cccd7c664b9529c',
    messagingSenderId: '511882466709',
    projectId: 'sugar-2474f',
    storageBucket: 'sugar-2474f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC92N_uPL1FiyNlc1at4oW4GxvfXCkWYNI',
    appId: '1:511882466709:ios:b25bd5e87760e732b9529c',
    messagingSenderId: '511882466709',
    projectId: 'sugar-2474f',
    storageBucket: 'sugar-2474f.appspot.com',
    iosBundleId: 'com.example.sugar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC92N_uPL1FiyNlc1at4oW4GxvfXCkWYNI',
    appId: '1:511882466709:ios:9e3a53a537b8f16db9529c',
    messagingSenderId: '511882466709',
    projectId: 'sugar-2474f',
    storageBucket: 'sugar-2474f.appspot.com',
    iosBundleId: 'com.example.sugar.RunnerTests',
  );
}
